import 'package:flutter/material.dart';

void main() {
  runApp(const TeacherAssistantApp());
  }

  class TeacherAssistantApp extends StatelessWidget {
    const TeacherAssistantApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  debugShowCheckedModeBanner: false,
                        title: 'Teacher Assistant',
                              theme: ThemeData(
                                      primarySwatch: Colors.blue,
                                              scaffoldBackgroundColor: const Color(0xFFF5F7FA),
                                                    ),
                                                          home: const DashboardScreen(),
                                                              );
                                                                }
                                                                }

                                                                class DashboardScreen extends StatelessWidget {
                                                                  const DashboardScreen({super.key});

                                                                    @override
                                                                      Widget build(BuildContext context) {
                                                                          return Scaffold(
                                                                                appBar: AppBar(
                                                                                        title: const Text('Teacher Assistant 📱'),
                                                                                                centerTitle: true,
                                                                                                        backgroundColor: Colors.indigo,
                                                                                                                elevation: 0,
                                                                                                                      ),
                                                                                                                            body: Padding(
                                                                                                                                    padding: const EdgeInsets.all(16.0),
                                                                                                                                            child: Column(
                                                                                                                                                      crossAxisAlignment: CrossAxisAlignment.start,
                                                                                                                                                                children: [
                                                                                                                                                                            const Text(
                                                                                                                                                                                          'مرحباً بك في نظام إدارة المدرس الذكي 👋',
                                                                                                                                                                                                        style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                const SizedBox(height: 20),
                                                                                                                                                                                                                                            Expanded(
                                                                                                                                                                                                                                                          child: GridView.count(
                                                                                                                                                                                                                                                                          crossAxisCount: 2,
                                                                                                                                                                                                                                                                                          crossAxisSpacing: 12,
                                                                                                                                                                                                                                                                                                          mainAxisSpacing: 12,
                                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                                            _buildCard(Icons.people, 'الطلاب', Colors.blue),
                                                                                                                                                                                                                                                                                                                                                              _buildCard(Icons.qr_code_scanner, 'الحضور (QR)', Colors.green),
                                                                                                                                                                                                                                                                                                                                                                                _buildCard(Icons.payment, 'المدفوعات', Colors.orange),
                                                                                                                                                                                                                                                                                                                                                                                                  _buildCard(Icons.assessment, 'التقارير', Colors.purple),
                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Widget _buildCard(IconData icon, String title, Color color) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elevation: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: InkWell(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onTap: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          CircleAvatar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        radius: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: color.withOpacity(0.15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: Icon(icon, size: 32, color: color),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              